### ISSUE TITLE
Have you ever tested your codes in other environments in the paper

### ISSUE THREAD

**Issue by yuanluzhan** [ku2482/wappo.pytorch#1]
I have run your code and it performs well on cartpole and it performed well. When I change the environment, howerer,  the return in both source domain and target domain are quite different to the results shown in the paper. Could you help me?

**Comment by rainprob** [comment]
你好 yuanluzhan 我在运行的时候出现了些问题 可以留个微信咨询一下吗

**Comment by toshikwa** [comment]
@yuanluzhan 
I haven't tested and I don't plan to do so.
However, I'd happy to help you if you can tell me more about it.

@rainprob 
I appreciate your help.

**Comment by yuanluzhan** [comment]
> 
> 
> 你好 yuanluzhan 我在运行的时候出现了些问题 可以留个微信咨询一下吗

哈哈哈哈可以，13521669927

**Comment by yuanluzhan** [comment]
> 
> 
> @yuanluzhan
> I haven't tested and I don't plan to do so.
> However, I'd happy to help you if you can tell me more about it.
> 
> @rainprob
> I appreciate your help.

thank you
