### ISSUE TITLE
Can't run with mistake of Xvfb 

### ISSUE THREAD

**Issue by rainprob** [ku2482/wappo.pytorch#2]
I run your code in 10 with all required environments but it fails.
![Capture](https://user-images.githubusercontent.com/63865505/100748139-ebd17200-341d-11eb-8fca-b89eec240229.PNG)

I don't know why Xvfb is needed (maybe you run it in server with no GUI I guess)
So, could you please tell me how to debug that?

**Comment by toshikwa** [comment]
@rainprob 
Please tell me more about your environment so that I can understand what is going on.
If you're using ubuntu, please install dependencies following the instruction below.
https://github.com/ponty/pyvirtualdisplay/tree/1.3.2#installation

Thanks.
